// This file is auto-generated by the build script
// Please, do not modify it manually

use super::{default_test_opts, test_markdown_html};
use pulldown_cmark::Options;

#[test]
fn emoji_short_code_test_1() {
    let original = r##":smile:
"##;
    let expected = r##"<p><span class="emoji-shortcode">smile</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_EMOJI_SHORTCODE);
    test_markdown_html(original, expected, opts);
}
