// This file is auto-generated by the build script
// Please, do not modify it manually

use super::{default_test_opts, test_markdown_html};
use pulldown_cmark::Options;

#[test]
fn mark_test_1() {
    let original = r##"==This is *mark out*==
"##;
    let expected = r##"<p><span class="markdown-mark">This is <em>mark out</em></span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_2() {
    let original = r##"==This is \=\=mark==
"##;
    let expected = r##"<p><span class="markdown-mark">This is ==mark</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_3() {
    let original = r##"This==is==mark
"##;
    let expected = r##"<p>This<span class="markdown-mark">is</span>mark</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_4() {
    let original = r##"==This==is==mark==
"##;
    let expected = r##"<p><span class="markdown-mark">This</span>is<span class="markdown-mark">mark</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_5() {
    let original = r##"Here I mark out an exclamation point==!==.
"##;
    let expected = r##"<p>Here I mark out an exclamation point<span class="markdown-mark">!</span>.</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_6() {
    let original = r##"==This is mark out==
"##;
    let expected = r##"<p><span class="markdown-mark">This is mark out</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_7() {
    let original = r##"==This is \=stricken==
"##;
    let expected = r##"<p><span class="markdown-mark">This is =stricken</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_8() {
    let original = r##"This=is=nothing
"##;
    let expected = r##"<p>This=is=nothing</p>
"##;

    let opts = default_test_opts();
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_9() {
    let original = r##"==This^is^superscript mark==
"##;
    let expected = r##"<p><span class="markdown-mark">This<sup>is</sup>superscript mark</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    opts.insert(Options::ENABLE_SUPERSCRIPT);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_10() {
    let original = r##"==This~is~subscript mark==
"##;
    let expected = r##"<p><span class="markdown-mark">This<sub>is</sub>subscript mark</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    opts.insert(Options::ENABLE_SUBSCRIPT);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_11() {
    let original = r##"==This~~is~~subscript mark==
"##;
    let expected = r##"<p><span class="markdown-mark">This<del>is</del>subscript mark</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_12() {
    let original = r##"Here I fail to mark out an exclamation point=!=.
"##;
    let expected = r##"<p>Here I fail to mark out an exclamation point=!=.</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_13() {
    let original = r##"Here I fail to mark out a tilde ==~.
"##;
    let expected = r##"<p>Here I fail to mark out a tilde ==~.</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_14() {
    let original = r##"Here I fail to match up ==tildes=.
"##;
    let expected = r##"<p>Here I fail to match up ==tildes=.</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_15() {
    let original = r##"Here I fail to match up =tildes==.
"##;
    let expected = r##"<p>Here I fail to match up =tildes==.</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_16() {
    let original = r##"==This =is mark.==
"##;
    let expected = r##"<p><span class="markdown-mark">This =is mark.</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_17() {
    let original = r##"=This ==is mark.=
"##;
    let expected = r##"<p>=This ==is mark.=</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_18() {
    let original = r##"====
"##;
    let expected = r##"<p>====</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_19() {
    let original = r##"This is == mark == test"##;
    let expected = r##"<p>This is == mark == test</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_20() {
    let original = r##"This is ==mark mark== test"##;
    let expected = r##"<p>This is <span class="markdown-mark">mark mark</span> test</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    test_markdown_html(original, expected, opts);
}

#[test]
fn mark_test_21() {
    let original = r##"==This**is** strong mark==
"##;
    let expected = r##"<p><span class="markdown-mark">This<strong>is</strong> strong mark</span></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_MARK);
    opts.insert(Options::ENABLE_SUPERSCRIPT);
    test_markdown_html(original, expected, opts);
}
